[theme]
base="light"
primaryColor="#0E1117"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"


[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = true

[ui]
hideTopBar = true
hideMenuItems = true
